[options]
girs_directories = ["../gir-files"]
work_mode = "sys"
library = "Soup"
version = "2.4"
min_cfg_version = "2.4"
target_path = "."

external_libraries = [
   "GLib",
   "GObject",
   "Gio",
]

